/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.*;
import java.text.SimpleDateFormat;
import java.io.FileNotFoundException;

/**
 *
 * @author falha
 */
public class bills extends javax.swing.JFrame{
    
    int bill_ID;
    int customerID;
    String discount="";
    Date bill_date= new Date();
   
    

    public bills(int cID,String discountType) {
        discount=discountType;
        customerID=cID;
        initComponents();
        fillTable();
        productTable.setDefaultEditor(Object.class, null);
        
    }
    
    Connection con;
    Statement st;
    ResultSet rs;
    

    private void fillTable() {
    try {
        
        con=DriverManager.getConnection("jdbc:derby://localhost:1527/products","project","12345");
        st=con.createStatement();
        rs=st.executeQuery("select * from Products");
        
        productTable.setModel(DbUtils.resultSetToTableModel(rs));
        productTable.removeColumn(productTable.getColumnModel().getColumn(6));
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null,e);
    }
    }
    public void closeDB()
    {          
         try                                          
         {                                            
            rs.close();                        
            st.close();                        
            con.close();                       
         }                                  
         catch (SQLException sqlException)          
         {                                            
            sqlException.printStackTrace();           
         }                                                             
    }
    
    double price, ptotal=0.0,total,dicountTotal,billTotal;
    int quantity, availableQty;
    
    int newQty,product_id;
    private void updateProduct(){
        try {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/products","project","12345");
            String query="Update Products set QUANTITY="+newQty+""+" where PRODUCTID="+product_id;
            Statement Add=con.createStatement();
            Add.executeUpdate(query);
            fillTable();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }                            
    public String ConvertDate(Date date){

    SimpleDateFormat billdate = new SimpleDateFormat("yyyy-MM-dd");
    String s = billdate.format(date);
    return s;
  }

    
    private void newBill(){
        try {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/products","project","12345");
            String query="insert into Bill values (?,?,?,?)";
            PreparedStatement insertBill=con.prepareStatement(query);
           
            String query2="Select bill_ID from bill";
            PreparedStatement getID=con.prepareStatement(query2);
            ResultSet rsID=getID.executeQuery();
            while(rsID.next())
                bill_ID=rsID.getInt("bill_ID")+1;
            
            insertBill.setInt(1, bill_ID);
            insertBill.setInt(2, customerID);
            insertBill.setString(3, ConvertDate(bill_date));
            insertBill.setDouble(4, billTotal);
            insertBill.executeUpdate();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        billingLabel = new javax.swing.JLabel();
        billingIcon = new javax.swing.JLabel();
        billingIcon1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextFeild = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        filterComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        quantityTextField1 = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        billTextArea = new javax.swing.JTextArea();
        logoutLabel = new javax.swing.JLabel();
        DoneButton = new javax.swing.JButton();
        nameLabel1 = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        discountLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(70, 157, 227));

        jPanel1.setBackground(new java.awt.Color(70, 157, 227));

        billingLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        billingLabel.setForeground(new java.awt.Color(255, 255, 255));
        billingLabel.setText("Billing");

        billingIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing/pics/bill.png"))); // NOI18N
        billingIcon.setIconTextGap(1);

        billingIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billingIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing/pics/logo.png"))); // NOI18N
        billingIcon1.setIconTextGap(1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Name");

        nameTextFeild.setEditable(false);
        nameTextFeild.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        nameTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFeildActionPerformed(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantityLabel.setText("Quantity");

        filterComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Beverages", "Dairy", "Bakery", "Grain", "Meat & Seafood", "Cleaners", "Produced", "Electrical" }));
        filterComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterComboBoxItemStateChanged(evt);
            }
        });
        filterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterComboBoxActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(70, 157, 227));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        quantityTextField1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        quantityTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextField1ActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(102, 102, 102));
        totalLabel.setText("Total");

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ProductID", "ProductName", "Price", "Quantity", "Category"
            }
        ));
        productTable.setRowHeight(20);
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        billTextArea.setEditable(false);
        billTextArea.setColumns(20);
        billTextArea.setRows(5);
        jScrollPane2.setViewportView(billTextArea);

        logoutLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing/pics/logout.png"))); // NOI18N
        logoutLabel.setText("logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        DoneButton.setBackground(new java.awt.Color(70, 157, 227));
        DoneButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoneButton.setText("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        nameLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel1.setText("Filter");

        discountLabel.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        discountLabel.setForeground(new java.awt.Color(102, 102, 102));

        discountLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        discountLabel2.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(discountLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 191, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoneButton)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discountLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutLabel))
                .addGap(24, 24, 24))
        );

        back.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        back.setForeground(new java.awt.Color(70, 157, 227));
        back.setText("New Order >>");
        back.setToolTipText("");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(billingIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billingIcon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(billingIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(billingLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billingIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int i=0;

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
     try {
           
        
          if(quantityTextField1.getText().isEmpty()||nameTextFeild.getText().isEmpty())
           {
             JOptionPane.showMessageDialog(this, "Missing Information");
            } 
         else if (availableQty<= (Integer.valueOf(quantityTextField1.getText()))){
             JOptionPane.showMessageDialog(this, "Not Enough In Stock");
            }
         else {
            quantity=Integer.valueOf(quantityTextField1.getText().trim()); 
            newQty=availableQty-Integer.valueOf(quantityTextField1.getText().trim()); 
            ptotal= price*quantity;
            i++;
            total=total+ptotal;
            
            
               if(i==1){
                billTextArea.setText(billTextArea.getText()
                +"=================CUSTOMER#"+customerID+"=================\n"
                        +"\t"+bill_date.toString()+"\n"
                +"=====================BILL=====================\n"
                +"NO\tPRODUCT\tPRICE\tQUANTITY\tTOTAL\n"
                +i+"\t"+nameTextFeild.getText()+"\t"
                +price+"\t" 
                +quantityTextField1.getText()+"\t"
                +ptotal+"\n");
                 }
               else {
                billTextArea.setText(billTextArea.getText()
                +i+"\t"+nameTextFeild.getText()+"\t"
                +price+"\t" 
                +quantityTextField1.getText()+"\t"
                +ptotal+"\n");    
                  }
            totalLabel.setText("Total        "+total+" SAR");
            billTotal=total;
            if (discount.equalsIgnoreCase("gold"))
            {
                dicountTotal=total-(total*0.5);
                discountLabel.setText("Discount 50%:  -"+String.format("%.2f",(total*0.5)));
                discountLabel2.setText("Total        "+dicountTotal+" SAR");
                billTotal=dicountTotal;
            }
            else if (discount.equalsIgnoreCase("silver")) {
                dicountTotal=total-(total*0.25);
                discountLabel.setText("Discount 25%:  -"+String.format("%.2f",(total*0.25)));
                discountLabel2.setText("Total        "+dicountTotal+" SAR");
                billTotal=dicountTotal;
            }else if(discount.equalsIgnoreCase("bronze")) {
                dicountTotal=total-(total*0.1);
                discountLabel.setText("Discount 10%:  -"+String.format("%.2f",(total*0.10)));
                discountLabel2.setText("Total        "+dicountTotal+" SAR");
                billTotal=dicountTotal;
            }
            
            updateProduct();
            
             }  
     }catch(NumberFormatException  e){
         JOptionPane.showMessageDialog(this, "Enter a Proper Number For Quantity","Incorrect Entry",JOptionPane.ERROR_MESSAGE);
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
     }
     finally {
        nameTextFeild.setText("");
        quantityTextField1.setText("");    
    }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void filterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterComboBoxActionPerformed

    private void nameTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFeildActionPerformed

    private void quantityTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextField1ActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
    closeDB();
    new Login().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
 
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        
        int index=productTable.getSelectedRow();
 
        product_id=Integer.valueOf(model.getValueAt(index, 0).toString().trim());
 
        nameTextFeild.setText(model.getValueAt(index, 1).toString().trim());
        if(quantityTextField1.getText().isEmpty())
            quantityTextField1.setText(1+"");
 
        availableQty=Integer.valueOf(model.getValueAt(index, 3).toString().trim());

        price = Double.valueOf(model.getValueAt(index, 2).toString().trim());
 
      
    }//GEN-LAST:event_productTableMouseClicked

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        if (billTextArea.getText().isEmpty()) 
            JOptionPane.showMessageDialog(null,"No Items Were Added To The Bill.","BILL EMPTY",JOptionPane.WARNING_MESSAGE);
        else {
        try {
           
            newBill();
            newFile();
            billTextArea.setText("");
            totalLabel.setText("Total");  
            discountLabel.setText("");
            discountLabel2.setText("");
            i=0;
        }
        catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void filterComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterComboBoxItemStateChanged
       try {
        
        con=DriverManager.getConnection("jdbc:derby://localhost:1527/products","project","12345");
        st=con.createStatement();
        if (filterComboBox.getSelectedItem().toString().equalsIgnoreCase("All"))
        {
            rs=st.executeQuery("select * from Products");
        }else                             
        { rs=st.executeQuery("select * from Products where CATEGORY= '"+filterComboBox.getSelectedItem().toString()+"'");}
        
        productTable.setModel(DbUtils.resultSetToTableModel(rs));
        productTable.removeColumn(productTable.getColumnModel().getColumn(6));
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_filterComboBoxItemStateChanged

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    new customer().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    
     private Formatter output;
    public  void openFile()
   {
      try 
      {
         output = new Formatter("bill"+(bill_ID)+".txt");
         
      }
      catch (SecurityException e)
      {
         System.err.println("Write permission denied. Terminating.");
      } 
       catch (FileNotFoundException e)
      {
         System.err.println("Error opening file. Terminating.");
      } 
   }
    public void closeFile() 
   {
         if (output != null)
            output.close(); 
  
   } 
    
    public  void newFile(){
        openFile();
        
            output.format (billTextArea.getText());
          if (discount.equals("none"))
              
            output.format(totalLabel.getText());
          else 
            output.format(discountLabel2.getText()); 
        
        closeFile();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bills(Integer.parseInt(customer.CustomerID.getText()),customer.mb.getText()).setVisible(true);
               
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton back;
    private javax.swing.JTextArea billTextArea;
    private javax.swing.JLabel billingIcon;
    private javax.swing.JLabel billingIcon1;
    private javax.swing.JLabel billingLabel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel discountLabel2;
    private javax.swing.JComboBox<String> filterComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameTextFeild;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField1;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

}
