/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package billing;

/**
 *
 * @author jodu
 */

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class products extends javax.swing.JFrame {
Connection con;
Statement st;
ResultSet rs;
String [] catarr = {"Dairy", "Beverages", "Bakery", "Grain", "Meat & Seafood", "Cleaners" , "Produced", "Electrical"};

    public products() {
        
        initComponents();
        filltable();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
//        addWindowListener(new WindowAdapter(){
//              @Override
//              public void windowClosed(WindowEvent event){
//                      closeDB();
//                      System.exit(0);
//              }//windowClosed
//           });
        
         ptable.setDefaultEditor(Object.class, null);
        
    }//constructor
    
    private void filltable(){
        
        try {
         
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/products", "project", "12345");
            st=con.createStatement();
               
            rs=st.executeQuery("select ProductID , ProductName , Price , Quantity , Category , Supplier FROM products"); 
            
            ptable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }

    public void closeDB()
    {    try                                          
         {                                            
            rs.close();                        
            st.close();                        
            con.close();                       
         }                                  
         catch (SQLException sqlException)          
         {                                            
            sqlException.printStackTrace();           
         }                                                             
    }//closeDB
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lid = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        lpp = new javax.swing.JLabel();
        lq = new javax.swing.JLabel();
        lc = new javax.swing.JLabel();
        ls = new javax.swing.JLabel();
        cbc = new javax.swing.JComboBox<>();
        tid = new javax.swing.JTextField();
        tn = new javax.swing.JTextField();
        ts = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        tq = new javax.swing.JTextField();
        editbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(70, 157, 227));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing/pics/logo.png"))); // NOI18N
        jLabel8.setToolTipText("");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lid.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lid.setText("Product ID:");

        ln.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ln.setText("Product Name:");

        lpp.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lpp.setText("Price");

        lq.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lq.setText("Quantity:");

        lc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lc.setText("Category:");

        ls.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ls.setText("Supplier:");

        cbc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dairy", "Baverages", "Bakery", "Grain", "Meat & Seafood", "Cleaners", "Produced", "Electrical" }));
        cbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcActionPerformed(evt);
            }
        });

        tid.setEditable(false);
        tid.setToolTipText("Cannot Edit, Automatic ID generation.");

        tn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(70, 157, 227));
        addbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("ADD");
        addbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addbtn.setBorderPainted(false);
        addbtn.setOpaque(true);
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        delbtn.setBackground(new java.awt.Color(70, 157, 227));
        delbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        delbtn.setForeground(new java.awt.Color(255, 255, 255));
        delbtn.setText("DELETE");
        delbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delbtn.setBorderPainted(false);
        delbtn.setOpaque(true);
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(215, 233, 248));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 157, 227));
        jLabel7.setText("Products");

        tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpActionPerformed(evt);
            }
        });

        tq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tqActionPerformed(evt);
            }
        });

        editbtn.setBackground(new java.awt.Color(70, 157, 227));
        editbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        editbtn.setForeground(new java.awt.Color(255, 255, 255));
        editbtn.setText("EDIT");
        editbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editbtn.setBorderPainted(false);
        editbtn.setOpaque(true);
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Price", "Quantity", "Category", "Supplier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ptable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lpp)
                                        .addGap(76, 76, 76))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ln)
                                            .addComponent(lid))
                                        .addGap(20, 20, 20)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tn)
                                    .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lc)
                                    .addComponent(ls)
                                    .addComponent(lq))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ts, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tq, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel7)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lq)
                            .addComponent(tq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lc)
                            .addComponent(tn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ln)
                            .addComponent(cbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lid)))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ls)
                    .addComponent(ts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpp)
                    .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(70, 157, 227));
        jButton1.setText("Log out");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
    
    if(tn.getText()=="" || tp.getText()=="" || tq.getText()=="" || tq.getText()=="")
    
        JOptionPane.showMessageDialog(null, "Missing info", null, JOptionPane.ERROR_MESSAGE);  
    
    else{ 
        try{
    int res = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete item?", null, JOptionPane.YES_NO_OPTION);
    if(res==JOptionPane.YES_OPTION){
    
    
    int lastrownum=ptable.getRowCount();
    String lastid=ptable.getModel().getValueAt(lastrownum-1, 0).toString();
        
    int check=st.executeUpdate("DELETE from products WHERE PRODUCTID="+tid.getText());
    
    //UPDATE ID NUMBER
    
    if(tid.getText()!=lastid){
    PreparedStatement ups = con.prepareStatement("UPDATE products SET ProductID=? WHERE ProductID=?");
   
    for(int i=Integer.valueOf(tid.getText()); i< lastrownum ; i++)
    {
            ups.setInt(1, i);
            ups.setInt(2, (i+1));
            ups.executeUpdate(); }
    
    }
    
    if(check==1)
    JOptionPane.showMessageDialog(null, "Item is deleted successfully", null, JOptionPane.INFORMATION_MESSAGE);
    
        tid.setText("");
        tn.setText("");
        tp.setText("");
        tq.setText("");
        cbc.setSelectedIndex(0);
        ts.setText("");
    
        
    closeDB();
    filltable();
    
    
    }//if statment
    
    
    }
    catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);        
            }    
   
    } 
    
    }//GEN-LAST:event_delbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
    if(tn.getText()=="" || tp.getText()=="" || tq.getText()=="" || tq.getText()=="")
    
        JOptionPane.showMessageDialog(null, "Missing info", null, JOptionPane.ERROR_MESSAGE);  
    
    else{    
        
        try {

            PreparedStatement pre=con.prepareStatement("INSERT INTO products VALUES (?,?,?,?,?,?,?) ");

            int lastrow=ptable.getRowCount();
            String lastid=ptable.getModel().getValueAt(lastrow-1, 0).toString();
            
            pre.setInt(1, Integer.valueOf(lastid)+1);
            pre.setString(2, tn.getText());
            pre.setDouble(3, Double.valueOf(tp.getText()));
            pre.setInt(4, Integer.valueOf(tq.getText()));
            pre.setString(5, cbc.getSelectedItem().toString());
            pre.setString(6, ts.getText());
            pre.setInt(7, Integer.valueOf(Login.Uid.getText()));

            int check =pre.executeUpdate();
            if(check==1)
            JOptionPane.showMessageDialog(null, "Item is added successfully", null, JOptionPane.INFORMATION_MESSAGE);

            closeDB();
            filltable();
            

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, null, JOptionPane.ERROR_MESSAGE);
        }
    }//if statement
                
    }//GEN-LAST:event_addbtnActionPerformed

        
    private void tnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnActionPerformed

    
    private void cbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcActionPerformed

    private void tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpActionPerformed

    private void tqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tqActionPerformed

    private void ptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptableMouseClicked
    try{
        int row = ptable.getSelectedRow();
        
        tid.setText(ptable.getModel().getValueAt(row, 0).toString());
        tn.setText(ptable.getModel().getValueAt(row, 1).toString());
        tp.setText(ptable.getModel().getValueAt(row, 2).toString());
        tq.setText(ptable.getModel().getValueAt(row, 3).toString());
        
        String cat =ptable.getModel().getValueAt(row, 4).toString();
        int catin=0 ;
        for(int i=0 ; i<8 ; i++)
        {if(cat.equals(catarr[i]))
            catin=i;
        }    
        cbc.setSelectedIndex(catin);
        
        ts.setText(ptable.getModel().getValueAt(row, 5).toString());
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e, null, JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ptableMouseClicked

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
    
        if(tn.getText()=="" || tp.getText()=="" || tq.getText()=="" || tq.getText()=="")
    
        JOptionPane.showMessageDialog(null, "Missing info", null, JOptionPane.ERROR_MESSAGE);  
    
    else{ 
        try {
        PreparedStatement ups = con.prepareStatement("UPDATE products SET ProductName=? , Price=?, Quantity=? , Category=? , Supplier=?, EID=? WHERE ProductID=?");
        
            ups.setString(1, tn.getText());
            ups.setDouble(2, Double.valueOf(tp.getText()));
            ups.setInt(3, Integer.valueOf(tq.getText()));
            ups.setString(4, cbc.getSelectedItem().toString());
            ups.setString(5, ts.getText());
            
            ups.setInt(6, Integer.valueOf(Login.Uid.getText())); //get his username
            ups.setInt(7, Integer.valueOf(tid.getText()));
            
            int check = ups.executeUpdate();
            
            closeDB();
            filltable();
            
            if(check==1)
            JOptionPane.showMessageDialog(null, "Item is updated successfully", null, JOptionPane.INFORMATION_MESSAGE);
            
         }//try
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, null, JOptionPane.ERROR_MESSAGE);
        }
        }//if statement 
    }//GEN-LAST:event_editbtnActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
   
        closeDB();
        new Login().setVisible(true);
        this.dispose();
               
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JComboBox<String> cbc;
    private javax.swing.JButton delbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lc;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel lpp;
    private javax.swing.JLabel lq;
    private javax.swing.JLabel ls;
    private javax.swing.JTable ptable;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tn;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField tq;
    private javax.swing.JTextField ts;
    // End of variables declaration//GEN-END:variables
}
